### ISSUE TITLE
Luca is noob

### ISSUE THREAD

**Issue by MrLucaDev** [MrLucaDev/OpenMT-Addon#6]
Luca is erg noob dat is een groot probleem

**Comment by MrLucaDev** [comment]
Probleem gefixed. Issue gesloten!

**Comment by TijsEijs** [comment]
dit is absoluut nog niet gefixt xD

**Comment by MrLucaDev** [comment]
F*ck off

**Comment by GideonDM** [comment]
Nice man :)

**Comment by TijsEijs** [comment]
serieus ? kick om dit ?
